### ISSUE TITLE
length of IEC101 parameters

### ISSUE THREAD

**Issue by afdard** [michaelxzhang/Wireshark_dissectors#1]
It would be nice to define length of the following parameters
Length of link address LA (currently 1 octet)
Length of common address CA (currently 1 octet)
Length of information object address IOA (currently 2 octets)
Length of cause of transmission COT (currently 1 octet)

Can the dissector be used with lengths other than the current defaults?
For example, its quite common to use length of CA = 2 octets, but your default is 1 octet

**Comment by michaelxzhang** [comment]
You can set these parameters from Wireshark menu: 
Edit -> Preferences -> Protocols -> IEC101

Please let me know if you have any questions.

**Comment by afdard** [comment]
Thanks for the info. There is also a fast menu available by right clicking on the packet -> protocol preferences -> and there they are...
